version: '3'
services:
  node-client:
    container_name: node-client
    hostname: node.client
    build:
      context: .docker/node-client
    ports:
    - "8080:8080"
    volumes:
    - ./:/usr/src/app
  node-server:
    container_name: node-server
    hostname: node.server
    build:
      context: .docker/node-server
    ports:
    - "8081:8081"
    volumes:
    - ./:/usr/src/app
